# Self-attention execution with debugging print statements

In [1]:
import torch
from self_attention import selfAttention,execute_self_attention


token_encodings = torch.tensor([[1.16,0.26],
              [0.57,1.36],
              [4.41,-2.16]])

execute_self_attention()

Executing self-attention with debug prints...

SELF-ATTENTION FORWARD PASS DEBUG

Input word encodings shape: torch.Size([3, 2])
Input word encodings:
tensor([[ 1.1600,  0.2600],
        [ 0.5700,  1.3600],
        [ 4.4100, -2.1600]])

--- Weight Matrices ---
W_q weight matrix shape: torch.Size([2, 2])
W_q weight matrix:
Parameter containing:
tensor([[ 0.5406,  0.5869],
        [-0.1657,  0.6496]], requires_grad=True)

W_k weight matrix shape: torch.Size([2, 2])
W_k weight matrix:
Parameter containing:
tensor([[-0.1549,  0.1427],
        [-0.3443,  0.4153]], requires_grad=True)

W_v weight matrix shape: torch.Size([2, 2])
W_v weight matrix:
Parameter containing:
tensor([[ 0.6233, -0.5188],
        [ 0.6146,  0.1323]], requires_grad=True)

--- Q, K, V Values ---
Q (queries) shape: torch.Size([3, 2])
Q (queries):
tensor([[ 0.7797, -0.0233],
        [ 1.1063,  0.7890],
        [ 1.1164, -2.1336]], grad_fn=<MmBackward0>)

K (keys) shape: torch.Size([3, 2])
K (keys):
tensor([[-0.1426, -0.2

tensor([[0.9704, 1.0498],
        [0.2001, 0.7072],
        [3.5010, 2.2447]], grad_fn=<MmBackward0>)

# Masked self attention with mask parameter being False

### This should match the result with the previous cell

In [1]:

from masked_self_attention import execute_masked_self_attention

execute_masked_self_attention(mask=False)

Executing self-attention with debug prints...



tensor([[0.9704, 1.0498],
        [0.2001, 0.7072],
        [3.5010, 2.2447]], grad_fn=<MmBackward0>)

# Masked self attention with mask parameter being True

In [3]:

from masked_self_attention import execute_masked_self_attention

execute_masked_self_attention(mask=True)

Executing self-attention with debug prints...



tensor([[ 0.5882,  0.7474],
        [-0.0096,  0.6091],
        [ 3.5010,  2.2447]], grad_fn=<MmBackward0>)